title: "PSRIO"
remote_theme: psrenergy/just-the-docs

#adding zoom in images
zoom_img_enabled: true

#dark/light mode
change_color_enabled: true
color_scheme: "dark"

# aux_links:
#   "PSRIO Scripts on GitHub":
#     - "//github.com/psrenergy/psrio-scripts"

ga_tracking: G-0EBJYPVP12
ga_tracking_anonymize_ip: true

back_to_top: true
back_to_top_text: "Back to top"
footer_content: "Copyright &copy; 2021 PSR - <a href='https://www.psr-inc.com' target='_blank'>psr-inc.com</a>"